### ISSUE TITLE
The deployment failed: Relative import path "$fresh/plugins/twind.ts" not prefixed with / or ./ or ../

### ISSUE THREAD

**Issue by christian-bromann** [denoland/deployctl#139]
Hey 👋 

just started trying out Deno with Fresh and wanted to deploy a website using the `deployctl` command. My setup is a fresh pulled Fresh project, no changes made. Running:

```
deployctl deploy --project=runme.dev main.ts
```

Fails with:

```
√ Project: xxx
i Uploading all files from the current dir (/Users/xxx/Sites/xxx/projects/xxx)
√ Found 17 assets.
√ No new assets to upload.
× Deployment failed.
error: The deployment failed: Relative import path "$fresh/plugins/twind.ts" not prefixed with / or ./ or ../
```

Anything I am missing?

**Comment by ayame113** [comment]
I think it's similar to this issue: https://github.com/denoland/fresh/issues/744

How about manually setting the `--import-map` flag?

**Comment by magurotuna** [comment]
As @ayame113 said, currently we need to explicitly tell deployctl the path of import map file with `--import-map`, because deployctl is not aware of deno.json right now. I am looking into this issue so I think it will be solved shortly. Meanwhile please use `--import-map`.

**Comment by christian-bromann** [comment]
Thanks, that did the trick!

**Comment by magurotuna** [comment]
@christian-bromann FYI the issue is now fixed. Now deployctl automatically discovers and interprets deno.json so you can deploy it without providing --import-map option.

**Comment by m0rphed** [comment]
Maybe it's just me doing things wrong, but I am still having this issue, deno-deploy does not `"imports"` section inside `deno.json`, I am having troubles with Hono project:

```json
{
  "imports": {
    "hono": "jsr:@hono/hono@^4.5.2",
    "@std/dotenv/load": "jsr:@std/dotenv/load"
  },
  "tasks": {
    "start": "deno run --allow-net --allow-read --allow-env main.ts"
  },
  "compilerOptions": {
    "jsx": "precompile",
    "jsxImportSource": "hono/jsx"
  },
  "deploy": {
    "exclude": [".env"],
    "include": ["./jsons", "*.ts"],
    "entrypoint": "./main.ts"
  }
}
```
main.ts:
```typescript
import { Hono } from "hono";
import { serveStatic } from "hono/deno";
import { cache } from "hono/cache";
import { cors } from "hono/cors";
import "@std/dotenv/load"
import { parseKnownCurrencies } from "./processData.ts";
import { CurrencyApiResponse } from "./types.ts";
...
```

I am getting:
```
× Deployment failed.
error: The deployment failed: Relative import path "@std/dotenv/load" not prefixed with / or ./ or ../
```

Which is strange for me - because locally with `deno task start` it all runs just fine on Deno version: `🦕 v1.45.4+8bab761`

- then is tried this:

```diff
import { Hono } from "hono";
import { serveStatic } from "hono/deno";
import { cache } from "hono/cache";
import { cors } from "hono/cors";
- import "@std/dotenv/load"
+ import "jsr:@std/dotenv/load"
import { parseKnownCurrencies } from "./processData.ts";
import { CurrencyApiResponse } from "./types.ts";
```

- and now I am getting: 
```
error: The deployment failed: Relative import path "hono/cors" not prefixed with / or ./ or ../
```
> but hono is definitely **in** my imports

And, again, locally it's all runs fine.. 😕
